environment:
  MINICONDA: "C:\\Miniconda"

platform: x86

configuration: Release

init:
  - set PATH=C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files (x86)\NSIS;%PATH%
  - conda create -n syncplay -y
  - activate syncplay
  - conda install python=3.5 -y
  - conda install pywin32 -y
  - conda install -c conda-forge pyside2 -y
  - pip install twisted pyinstaller zope.interface
  - type nul > C:\Miniconda\envs\syncplay\lib\site-packages\zope\__init__.py
  - pip freeze
  - conda list
  
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - for /F "tokens=2 delims='" %%a in ('findstr version syncplay\__init__.py') do @set ver=%%a
  - pyinstaller pyinstaller-onefile.spec
  - move dist\Syncplay.exe Syncplay-%ver%-win-Py3-PySide2.exe
  - del build /s /Q
  - del dist /s /Q
  - pyinstaller pyinstaller-onedir.spec

# Not a project with an msbuild file, build done at install.
build: off

artifacts:
  - path: 'dist'
    type: zip
    name: Syncplay-$(ver)-win-py3-pyside2

  - path: Syncplay-$(ver)-win-Py3-PySide2.exe
    name: Syncplay-$(ver)-win-py3-pyside2

# Push artefact to S3 bucket and list all
before_deploy:
  - dir
  #- python -c "from PySide2 import QtCore; print QtCore.QLibraryInfo.location(QtCore.QLibraryInfo.PluginsPath)"


# Deploy build to BinTray
deploy:
  provider: BinTray
  username: alby128
  api_key:
    secure: lAocj5KA9Z9x4BefQBIgNlQJbeW4qPBfCgYVBHMyOP3NgyhnMLmvR57ZCqtCKBlQ
  subject: alby128
  repo: Syncplay
  package: Syncplay
  version: "test"
  publish: true
  override: true
    