environment:
  MINICONDA: "C:\\Miniconda"

platform: x86

configuration: Release

init:
  - set PATH=C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files (x86)\NSIS;%PATH%
  - conda create -n syncplay -y
  - activate syncplay
  - conda install python pywin32 pyside -y
  - pip install twisted py2exe_py2 zope.interface
  - type nul > C:\Miniconda\envs\syncplay\lib\site-packages\zope\__init__.py
  - pip freeze
  - conda list
  
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - for /F "tokens=2 delims='" %%a in ('findstr version syncplay\__init__.py') do @set ver=%%a
  - python buildPy2exe.py
  - del syncplay_v%ver%\lib\MPR.dll
  - type nul > syncplay_v%ver%\syncplay.ini
  - copy resources\win_lua_note.txt syncplay_v%ver%\"VLC LUA Script installation.txt"

# Not a project with an msbuild file, build done at install.
build: off

artifacts:
  - path: 'syncplay_v$(ver)'
    type: zip
    name: Syncplay_v$(ver)_Portable

  - path: Syncplay-$(ver)-Setup.exe
    name: Syncplay-$(ver)-win-setup

# Push artefact to S3 bucket and list all
before_deploy:
  - dir
  - dir syncplay_v%ver%
  #- python -c "from PySide2 import QtCore; print QtCore.QLibraryInfo.location(QtCore.QLibraryInfo.PluginsPath)"


# Deploy build to BinTray
deploy:
  provider: BinTray
  username: etoh
  api_key: 
    secure: TfwB161OlDOcAz5nnmjtNjDmJw2KyCz/uB1KzN4r5/9AL3uczWNuY+k6qVGaRvOP
  repo: Syncplay
  package: Syncplay
  subject: syncplay
  version: v$(ver)
  publish: true
  override: true